### ISSUE TITLE
create-dosbox failing every time

### ISSUE THREAD

**Issue by jadenquinn** [js-dos/create-dosbox#1]
Hi, I for some reason had to reinstall NPM and NPX, and in turn, JS-DOS. This didn't seem to be an issue at first, but something happened, as "npx create-dosbox wolf3d wolf3d.zip" no longer works.

![image](https://user-images.githubusercontent.com/13245331/98361336-33f8a280-1fe0-11eb-9bf4-a49507c9b92d.png)

**Comment by caiiiycuk** [comment]
Works for me, maybe create-dosbox is not compatible with your version of node. Which version of node do you use.

**Comment by jadenquinn** [comment]
I just downloaded whatever normal version there was, so I can only assume it's 15.5.0 but it could have been the 14 version.

**Comment by jadenquinn** [comment]
I was able to do it before, just not now, here's the few I did before: http://jadenswebmc.us.to/pub_cdn/apps/

**Comment by caiiiycuk** [comment]
Should be fixed with create-dosbox@7.0.10

**Comment by jadenquinn** [comment]
Thank you.
