### ISSUE TITLE
Facing an issue "js-dos.ts:73 DOMException: Failed to construct 'Worker': Script at 'https://js-dos.com/v7/build/releases/latest/emulators/wdosbox.js' cannot be accessed from origin "https://www.xyz.com"

### ISSUE THREAD

**Issue by bhushans-professional** [js-dos/create-dosbox#3]
I am trying to implement a dos program on a web page using js-dos api. But facing an error saying "js-dos.ts:73 DOMException: Failed to construct 'Worker': Script at 'https://js-dos.com/v7/build/releases/latest/emulators/wdosbox.js' cannot be accessed from origin "xyz.com".

Below is the screenshot for the same:

![image](https://user-images.githubusercontent.com/85776823/128554466-7f424657-8d6b-4173-ac03-e4093ce200c0.png)

Here is the js-dos API script I am using:
```
<!doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <style>
         html, body, #jsdos {
             width: 100%;
             height: 100%;
             margin: 0;
             padding: 0;
         }
        </style>
        <script src="https://js-dos.com/v7/build/releases/latest/js-dos/js-dos.js"></script>
        <link href="https://js-dos.com/v7/build/releases/latest/js-dos/js-dos.css" rel="stylesheet">
    </head>
    <body>
        <div id="jsdos" ></div>
        <script>
         emulators.pathPrefix = "https://js-dos.com/v7/build/releases/latest/js-dos/";
         Dos(document.getElementById("jsdos")).run("http://www.xyz.com/HTSTPASS.jsdos");
        </script>
    </body>
</html>

```
I tried solutions from other sources but nothing worked. Can somebody please help with this or lead me in to correct direction?

Many Thanks!!

**Comment by caiiiycuk** [comment]
Hi, you need to host jsdos on your site (xyz)

**Comment by bhushans-professional** [comment]
> Hi, you need to host jsdos on your site (xyz)

@caiiiycuk Thanks for commenting.
I had uploaded `.jsdos` file to the server where my site is hosted.  But that didn't work. I am totally a novice to jsdos libraries.
Do I have to install `jsdos` library over the server where my site is hosted? Is there any documentation related to this?
