### ISSUE TITLE
Bundle Local ZIP archive issue

### ISSUE THREAD

**Issue by SiegeMstr** [js-dos/create-dosbox#4]
Attempting to use this code: (from https://www.npmjs.com/package/create-dosbox/v/6.22.41)

Or if you have ZIP archive with dos program you can bootstrap it:

npx create-dosbox my-app archive.zip
cd my-app
npm install
npm start

I have a zip archive I would like to use but it continues to ask for the game in your repository. The game I am trying to get working is not in your repository.

Does it have to be named "archive.zip" or should it work with any zip file?

**Comment by caiiiycuk** [comment]
Hi
use npx create-dosbox my-app
then select game from repository (e.g. Digger), after that
replace jsdos file inside my-app/_site folder with your zip

ср, 15 сент. 2021 г. в 23:23, MrTeacherMan ***@***.***>:

**Comment by SiegeMstr** [comment]
do I need to change the archive name to what the jsdos file was named?

**Comment by SiegeMstr** [comment]
Did not work. But also discovered the issue is with the archive. It is not technically a Dos program....
